version: 2

project_name: testapp

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ tolower .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ tolower .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: github

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

blobs:
  - provider: s3
    endpoint: "{{ .Env.BUILD_ARTIFACTS_S3_ENDPOINT }}"
    region: "{{ .Env.BUILD_ARTIFACTS_S3_REGION }}"
    bucket: "{{ .Env.BUILD_ARTIFACTS_S3_BUCKET }}"
    directory: prac-goreleaser-and-tagpr-with-actions/releases/v{{ .Version }}
