version: 2

project_name: test

before:
  hooks:
    - go mod tidy

builds:
  - id: hoge
    main: .
    binary: hoge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ tolower .ProjectName }}_
      {{- tolower .Binary }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "386" }}i386{{ else }}{{ tolower .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  use: github

blobs:
  - provider: s3
    endpoint: "{{ .Env.BUILD_ARTIFACTS_S3_ENDPOINT }}"
    region: "{{ .Env.BUILD_ARTIFACTS_S3_REGION }}"
    bucket: "{{ .Env.BUILD_ARTIFACTS_S3_BUCKET }}"
    directory: prac-goreleaser-and-tagpr-with-actions/releases/v{{ .Version }}
