on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on:
      - ubuntu-latest

    container:
      image: ubuntu:24.04
      env:
        TZ: "Asia/Tokyo"

    steps:
      # NOTE: コンテナを使うとディレクトリの所有者がホスト側のuid, gidに設定されている。そのため、コンテナ内で再設定する。
      - name: Set permissions
        run: |
          chown -R root:root ..

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y tzdata git

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_ARTIFACTS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_ARTIFACTS_S3_SECRET_ACCESS_KEY }}
          AWS_REQUEST_CHECKSUM_CALCULATION: when_required
          AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
          BUILD_ARTIFACTS_S3_ENDPOINT: ${{ vars.BUILD_ARTIFACTS_S3_ENDPOINT }}
          BUILD_ARTIFACTS_S3_REGION: ${{ vars.BUILD_ARTIFACTS_S3_REGION }}
          BUILD_ARTIFACTS_S3_BUCKET: ${{ vars.BUILD_ARTIFACTS_S3_BUCKET }}
          PR_NUMBER: ${{ github.event.number }}
